name: Format
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - name: Run clang-format
        run: |
          # shellcheck disable=SC2046
          clang-format --dry-run -Werror $(git ls-files '**.hpp' '**.cpp')
      - name: Save format patch
        if: failure()
        run: |
          # shellcheck disable=SC2046
          clang-format -i $(git ls-files '**.hpp' '**.cpp')
          git diff | tee clang-format.patch
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: clang-format
          path: clang-format.patch
  clang-tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '>=3.0.1'
          actions-cache-folder: .xmake-cache
          package-cache: true
          package-cache-key: ubuntu-latest
          project-path: glug
      - run: pip install -r requirements.txt
      - name: Pull dependencies
        run: xmake config -vy
      - name: Generate compilation DB
        run: xmake project -k compile_commands
      - name: Run clang-tidy
        run: |
          # shellcheck disable=SC2046
          clang-tidy $(git ls-files '**.hpp' '**.cpp')
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - run: flake8
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements.txt
      - run: mypy

